; [pytest]
; log_cli = true
; log_cli_level = INFO

; log_file = logs/test.log
; log_file_level = INFO

; log_format = %(asctime)s [%(levelname)s] %(message)s
; log_date_format = %Y-%m-%d %H:%M:%S

[pytest]
log_cli = true
log_cli_level = INFO